import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'

export const config = {
  runtime: 'experimental-edge',
}

function Home() {
  const [data, setData] = useState({});

  useEffect(() => {
    fetch('/api/hello')
    .then(response =>  response.json())
    .then(response => setData(response) );
  }, []);


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
          <h1> { data?.logradouro }, {data?.bairro} - { data?.localidade } / {data?.uf} </h1>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}

// This gets called on every request
// export async function getServerSideProps() {
//   // Fetch data from external API
//   const res = await fetch(`http://localhost:3000/api/hello`);
//   const data =  await res.json();

//   // Pass data to the page via props
//   return { props: { data } }
// }


export default Home;
